### ISSUE TITLE
Validate DBpedia taxonomisation

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/dap_aria_mapping#12]
Assessing between methods

**Comment by ampudia19** [comment]
I presume it's best both Emily and I are assigned to this one.

**Comment by emily-bicks** [comment]
Methods to assess the quality of the taxonomy groupings:
- [ ] distribution of tokens per group (if the distribution is too skewed it likely won't be useful for our purposes)

**Comment by ampudia19** [comment]
- [x] Apply taxonomy to & validate on ARIA DBpedia entities.
- [ ] Make a selection on the final taxonomy.
- [ ] **Code refactoring**: Are we still opting for generators?

**Comment by emily-bicks** [comment]
Potential validation metrics:
- Skewness of distribution of entities/topics
- Depth of trees
- Number of topics / journal
- Relative difference in variance of embeddings / level
- Variance of resulting taxonomy based on initialisation / hyperparameters / introducing noise and checking if known words are always ending up in the same category
- Measure stability with different sample sizes: distribution of
