### ISSUE TITLE
Naming DBpedia taxonomy groups

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/dap_aria_mapping#13]
Generate names for DBpedia clusters. At the highest level, we can use manual labelling. At lower levels, we will probably want to use automated methods. Some options include:

- Highest tfidf based on entity frequencies acros corpora
- Use most central terms based on average semantic similarity (similar to the way BERTopic works I think)
- Use [cohere](https://github.com/cohere-ai/sandbox-topically)

**Comment by ampudia19** [comment]
I'm happy taking care of this one and exploring the alternatives above.

**Comment by emily-bicks** [comment]
@ampudia19 - maybe we can do this in a similar method that we discussed for issues 9/10? i.e. we architect it together so the functions take the same inputs/outputs and then we divide and conquer the methods and evaluate them together?

**Comment by ampudia19** [comment]
Happily :)

**Comment by ampudia19** [comment]
I've implemented the entity count as well as a weighted count of journal relevance per sub-topic (this provides some exogenous labelling of the topics). I'm happy to explore the remaining ones here.
