### ISSUE TITLE
Generate scores for share of topics across publications and patents

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/dap_aria_mapping#14]

**Comment by emily-bicks** [comment]
- [x] tag documents with topics at each level
- [ ] absolute counts of topics
- [ ] proportions of topics
- [ ] focus on specific areas - manual search for topics that have things like ML/AI, and look at the composition of those
- [ ] compare institutions of who is completing that work in publications vs. patents
- [ ] analyse co-occurance of topics
