### ISSUE TITLE
Validation: Number of topics per journal

### ISSUE THREAD

**Issue by ampudia19** [nestauk/dap_aria_mapping#44]
![Image](https://user-images.githubusercontent.com/61916660/214531127-082be8e2-efc2-4eb7-a00b-3fef8cde3223.png)

Validate that topic-specific journals are well captured by a handful of relevant topics, that similarly break down in relevant topics. This builds from the sunbursts generated in #12.

NB. This also corresponds to bullet point "Number of topics / journal" in the same issue.

**Comment by emily-bicks** [comment]
- produce distributions
- come up with statistics
