### ISSUE TITLE
Tag patents and publications with DBpedia entities

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/dap_aria_mapping#5]
- [x] Apply pre- and post-processing
- [x] Getter(s)
- [x] Generate files for tagging
- [x] Store results on S3

**Comment by Jack-Vines** [comment]
Files have now been generated:
`s3://aria-mapping/data_collection/processed_openalex/abstracts_for_annotation.json`
`s3://aria-mapping/data_collection/patents/patents_for_annotation.json`

**Comment by india-kerle** [comment]
N.B. I think the processing will just be about having a higher confidence threshold
