### ISSUE TITLE
Write data collection pipeline for publications and collect

### ISSUE THREAD

**Issue by georgerichardson** [nestauk/dap_aria_mapping#7]
- [ ] Write pipeline to collect:
  - All publications involving a UK author
  - Between 2016 and 2021 inclusive (as a minimum)
- [ ] Store data
- [ ] Getter(s)

**Comment by ampudia19** [comment]
Am I right in assuming these pipelining tasks should be tackled by India/Jack? I'm otherwise very happy to lend a hand in building them.

**Comment by georgerichardson** [comment]
Clarified in the meeting:

- Jack and India mainly responsible for data collection pipelines (although additional help might be needed)
- Pipelines for data processing/science parts to be written after prototyping stage
- Updated this issue name to be clearer
